theme: jekyll-theme-minimal
title: Wuyang's Tech Notes
description: Machine Learning Learning Projects
markdown: GFM
author: Wuyang Li
url: "https://wuyangli.github.io"
permalink: /:categories/:year/:month/:day/:title:output_ext
show_excerpts: true
collections:
  posts:
    output: true
    permalink: /:title/
